version: '3'

services:
  app:
    build: .
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=psql://postgres:postgres@db/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - MEDIA_ROOT=/var/media
    volumes:
      - "./media:/var/media"
  celery:
    build: .
    command: ./entrypoint_celery.sh
    depends_on:
      - db
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=psql://postgres:postgres@db/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - MEDIA_ROOT=/var/media
    volumes:
      - "./media:/var/media"
  rabbitmq:
    image: rabbitmq
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./db:/var/lib/postgresql/data"