version: '3'

services:
  app:
    build: .
    command: ./entrypoint.sh
    depends_on:
      - db
      - rabbitmq
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=psql://postgres:postgres@db/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - MEDIA_ROOT=/var/media
    volumes:
      - "./media:/var/media"
  celery:
    build: .
    command: ./entrypoint_celery.sh
    depends_on:
      - db
      - rabbitmq
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=psql://postgres:postgres@db/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - MEDIA_ROOT=/var/media
    volumes:
      - "./media:/var/media"
  rabbitmq:
    image: rabbitmq
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./db:/var/lib/postgresql/data"
  nginx:
    image: "nginx:stable"
    volumes:
      - "./media:/var/media"
      - "./nginx:/etc/nginx:ro"
    ports:
      - "80:80"